---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

platforms:
- name: centos-7.3
  run_list: recipe[yum-epel]
- name: centos-6.8
  run_list: recipe[yum-epel]
- name: centos-5.11
  run_list: recipe[yum-epel]
- name: ubuntu-16.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-13.10
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: debian-8.7
  run_list: recipe[apt]
- name: debian-7.10
  run_list: recipe[apt]

suites:
  - name: install_package
    run_list:
    - recipe[minitest-handler]
    - recipe[duplicity_ng::package]
    - recipe[duplicity_ng::install_azure]
    - recipe[duplicity_ng::install_boto]
    - recipe[duplicity_ng::install_ftp]
    - recipe[duplicity_ng::install_paramiko]
    - recipe[duplicity_ng::install_par2]
    - recipe[duplicity_ng::install_swift]
    attributes:
      duplicity_ng:
        use_pip: false
  - name: install_package_pip
    run_list:
    - recipe[minitest-handler]
    - recipe[duplicity_ng::package]
    - recipe[duplicity_ng::install_azure]
    - recipe[duplicity_ng::install_boto]
    - recipe[duplicity_ng::install_ftp]
    - recipe[duplicity_ng::install_paramiko]
    - recipe[duplicity_ng::install_par2]
    - recipe[duplicity_ng::install_swift]
    attributes:
      duplicity_ng:
        use_pip: true
  - name: install_source
    run_list:
    - recipe[minitest-handler]
    - recipe[duplicity_ng::source]
    - recipe[duplicity_ng::install_azure]
    - recipe[duplicity_ng::install_boto]
    - recipe[duplicity_ng::install_ftp]
    - recipe[duplicity_ng::install_paramiko]
    - recipe[duplicity_ng::install_par2]
    - recipe[duplicity_ng::install_swift]
    attributes:
      duplicity_ng:
        path: duplicity
        use_pip: false

  - name: install_source_pip
    run_list:
    - recipe[minitest-handler]
    - recipe[duplicity_ng::source]
    - recipe[duplicity_ng::install_azure]
    - recipe[duplicity_ng::install_boto]
    - recipe[duplicity_ng::install_ftp]
    - recipe[duplicity_ng::install_paramiko]
    - recipe[duplicity_ng::install_par2]
    - recipe[duplicity_ng::install_swift]
    attributes:
      duplicity_ng:
        path: duplicity
        use_pip: true
