---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-6.5
  run_list: recipe[yum-epel]
- name: centos-5.9
  run_list: recipe[yum-epel]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-13.10
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: debian-7.2.0
  run_list: recipe[apt]

suites:
  - name: install_package
    run_list:
    - recipe[minitest-handler]
    - recipe[duplicity_ng::package]

  - name: install_source
    run_list:
    - recipe[minitest-handler]
    - recipe[duplicity_ng::source]
    attributes:
      duplicity_ng:
        path: /usr/bin/duplicity
        source:
          use_pip: false

  - name: install_source_pip
    run_list:
    - recipe[minitest-handler]
    - recipe[python::pip]
    - recipe[duplicity_ng::source]
    attributes:
      duplicity_ng:
        path: /usr/bin/duplicity
        source:
          use_pip: true
